# Generated by Django 3.2.7 on 2021-11-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inwarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inw_item_name', models.CharField(max_length=200)),
                ('inw_location', models.CharField(max_length=200)),
                ('inw_description', models.CharField(max_length=200)),
                ('inw_make_model', models.CharField(max_length=200)),
                ('inw_quantity', models.IntegerField()),
                ('inw_vendor_name', models.CharField(max_length=200)),
                ('inw_date_of_purchase', models.DateField(max_length=200)),
                ('inw_sourcing_department', models.CharField(max_length=200)),
                ('inw_unit_cost', models.IntegerField()),
                ('inw_category', models.CharField(max_length=200)),
                ('inw_type', models.CharField(max_length=200)),
                ('inw_remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
