# Generated by Django 3.2.7 on 2021-11-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211109_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarding',
            name='inw_admin_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inwarding',
            name='inw_finance_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inwarding',
            name='inw_category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inwarding',
            name='inw_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inwarding',
            name='inw_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inwarding',
            name='inw_sourcing_department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inwarding',
            name='inw_type',
            field=models.CharField(max_length=200),
        ),
    ]
