# Generated by Django 3.2.7 on 2021-11-16 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211110_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarding',
            name='inw_date_of_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
