# Generated by Django 3.2.7 on 2021-11-16 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_inwarding_inw_date_of_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_department', models.CharField(choices=[('MANAGEMENT', 'MANAGEMENT'), ('OPERATIONS', 'OPERATIONS'), ('T&S', 'T&S'), ('E&M', 'E&M'), ('S&S', 'S&S'), ('FCN', 'FCN')], default='MANAGEMENT', max_length=200)),
                ('user_filter_group', models.CharField(choices=[('HOD', 'HOD'), ('FINANCE', 'FINANCE'), ('MANAGEMENT', 'MANAGEMENT'), ('ADMIN', 'ADMIN')], default='HOD', max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
