# Generated by Django 3.2.7 on 2021-11-16 11:37

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_filtering'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarding',
            name='inw_owner',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
        migrations.AlterField(
            model_name='filtering',
            name='user_filter_group',
            field=models.CharField(choices=[('HOD', 'HOD'), ('FINANCE', 'FINANCE'), ('EMPLOYEE', 'EMPLOYEE'), ('ADMIN', 'ADMIN')], default='HOD', max_length=200),
        ),
        migrations.AlterField(
            model_name='inwarding',
            name='inw_date_of_entry',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
