# Generated by Django 3.2.7 on 2021-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20211116_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwarding',
            name='inw_owner',
            field=models.CharField(max_length=200),
        ),
    ]
