# Generated by Django 3.2.7 on 2021-11-16 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_inwarding_inw_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarding',
            name='inw_user_group',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inwarding',
            name='inw_date_of_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
