# Generated by Django 3.2.7 on 2021-11-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20211116_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarding',
            name='inw_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='filtering',
            name='user_filter_group',
            field=models.CharField(choices=[('HOD', 'HOD'), ('FINANCE', 'FINANCE'), ('EMPLOYEE', 'EMPLOYEE')], default='HOD', max_length=200),
        ),
    ]
