# Generated by Django 3.2.7 on 2021-11-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20211122_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtering',
            name='user_filter_group',
            field=models.CharField(choices=[('HOD', 'HOD'), ('FINANCE', 'FINANCE'), ('EMPLOYEE', 'EMPLOYEE'), ('ADMIN', 'ADMIN')], default='HOD', max_length=200),
        ),
    ]
