# Generated by Django 3.2.7 on 2021-11-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_filtering_user_filter_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwarding',
            name='inw_img',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
