# Generated by Django 3.2.7 on 2021-12-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_inwarding_inw_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtering',
            name='user_department',
            field=models.CharField(choices=[('MANAGEMENT', 'MANAGEMENT'), ('OPERATIONS', 'OPERATIONS'), ('T&S', 'T&S'), ('NAVAC', 'NAVAC'), ('E&M', 'E&M'), ('S&S', 'S&S'), ('FCN', 'FCN')], default='MANAGEMENT', max_length=200),
        ),
        migrations.AlterField(
            model_name='inwarding',
            name='inw_make_model',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
